# paths
label_csv: "multilabel_classification/train.csv"
coco_train_json: "object_detection/train.json"  # contains coco_url with dive_id
category_key_csv: "./src/dataset/category_key.csv"
image_dir: "images"  # folder with uuid.png

# data
img_ext: ".png"
image_size: 224
val_ratio: 0.2
seed: 42

# dataloader
batch_size: 32
num_workers: 4
pin_memory: false # set true when using GPU

# training
quick_test: true # if true, use only first 100 samples for quick testing
save_model: false

# grid search
grid_search: true
grid_params:
  learning_rate: [0.001, 0.0001, 0.00001]
  batch_size: [32, 64]
  freeze: [true, false]
  smoothing_epsilon: [0.0, 0.05]
  optimizer: [AdamW]
  loss_fn: [BCEWithLogits]
  model_name: [resnet50_baseline, vit_baseline]
  num_epochs: [50]
  unfreeze_epoch: [20]
  pos_weight: [2.0]
  early_stopping_patience: [3]
  early_stopping_min_delta: [0.01]
  layer_size: [256, 512]