# paths
label_csv: "multilabel_classification/train.csv"
coco_train_json: "object_detection/train.json"  # contains coco_url with dive_id
category_key_csv: "./src/dataset/category_key.csv"
image_dir: "images"  # folder with uuid.png

# data
img_ext: ".png"
image_size: 224
val_ratio: 0.2
seed: 42

# dataloader
batch_size: 32
num_workers: 4
pin_memory: true

# training
quick_test: true # if true, use only first 100 samples for quick testing