# model name
model_name: resnet50_baseline
layer_size: 256

freeze: true
num_epochs: 50
learning_rate: 0.001
lr_step_size: 5
lr_gamma: 0.1
weight_decay: 0
loss_fn: BCEWithLogits
optimizer: AdamW
unfreeze_epoch: 5
smoothing_epsilon: 0

# early stopper
patience: 3
min_delta: 0.0

# inference transforms
resize_size: 256
crop_size: 224
rescale: [0.0, 1.0]
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

# augmentations
augmentations:
  horizontal_flip: 0.5
  rotation_limit: 7
  rotation_prob: 0.2
  brightness_contrast: 0.3
  hue_saturation: 0.15
  gauss_noise: [0.1, 0.2]
  gauss_noise_prob: 0.2

# interpolation
interpolation: BILINEAR