# model name
model_name: vit_baseline

freeze: true
num_epochs: 50
learning_rate: 0.001
weight_decay: 0.01
loss_fn: BCEWithLogits
optimizer: AdamW

# early stopper
patience: 1
min_delta: 0.0

# inference transforms
resize_size: 256
crop_size: 224
rescale: [0.0, 1.0]
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

# augmentations
augmentations:
  horizontal_flip: 0.5
  rotation_limit: 10
  rotation_prob: 0.3
  brightness_contrast: 0.5
  hue_saturation: 0.2
  gauss_noise: [0.2, 0.4]
  gauss_noise_prob: 0.3

# interpolation
interpolation: BILINEAR